name: Carbon Credits API Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: true
        default: "@smoke"
        type: choice
        options:
          - @smoke
          - @sanity
          - @regression
      environment:
        description: "Environment to run tests against"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stg
          - prod

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: corepack enable
      - name: deps installation
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: | 
          echo "TEST TAGS: $TEST_TAGS"
          echo "TEST ENV: $TEST_ENV"
          echo "LOG LEVEL: $LOG_LEVEL"
          echo "CI: $CI"
          pnpm test:run
        env:
          TEST_TAGS: ${{ inputs.tags }}
          TEST_ENV: ${{ inputs.environment }}
          LOG_LEVEL: ${{ inputs.logLevel }}
          CI: 1
